---
- name: Solve Lab 4
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
  - ../vars.yml
      
  tasks:
    - name: deploy inventory in {{ dev_project }}
      shell: "oc new-app inventory-mockup -n {{ dev_project }}"
      ignore_errors: true
    - name: create temporary git directory
      tempfile:
        state: directory
        prefix: catalog-git
      register: git_dir

    - name: Get database user
      shell: "oc env dc/catalog-postgresql --list | grep POSTGRESQL_USER | cut -d'=' -f2"
      register: cmd_output

    - set_fact: postgresql_user={{cmd_output.stdout}}
    
    - name: Get database password
      shell: "oc env dc/catalog-postgresql --list | grep POSTGRESQL_PASSWORD | cut -d'=' -f2"
      register: cmd_output

    - set_fact: postgresql_password={{cmd_output.stdout}}
    
    - name: Update the configmap
      shell:
        cmd: |
          cat <<EOF | oc replace -f - -n {{ dev_project }}
          apiVersion: v1
          data:
            application.properties: |
              server.port=8080
              spring.application.name=catalog
              feign.hystrix.enabled=false
              spring.datasource.url=jdbc:postgresql://catalog-postgresql:5432/catalog
              spring.datasource.username={{ postgresql_user }}
              spring.datasource.password={{ postgresql_password }}
              spring.datasource.driver-class-name=org.postgresql.Driver
              spring.jpa.hibernate.ddl-auto=create
              ribbon.listOfServers=inventory:8080
          kind: ConfigMap
          metadata:
            labels:
              app: catalog
            name: catalog
          EOF
      ignore_errors: true

    - name: clone catalog git repository
      shell: "git clone http://{{ gogs_user }}:{{ gogs_password }}@{{ gogs_hostname }}/{{ gogs_user }}/catalog.git"
      args:
        chdir: "{{ git_dir.path }}"

    - name: copy catalog source code
      copy:
        src: catalog/
        dest: "{{ git_dir.path }}/catalog/"

    - name: push catalog source code git repository
      shell: |
        git config user.email "rhdeveloper@redhat.com"
        git config user.name "rh-developer"
        git add --all
        git commit -m "connected catalog to inventory"
        git push origin master
      args:
        chdir: "{{ git_dir.path }}/catalog"