---
- name: Solve Lab 4
  hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
  - ../vars.yml
      
  tasks:
    - name: create temporary git directory
      tempfile:
        state: directory
        prefix: catalog-git
      register: git_dir

    - name: clone catalog git repository
      shell: "git clone http://{{ gogs_user }}:{{ gogs_password }}@{{ gogs_hostname }}/{{ gogs_user }}/catalog.git"
      args:
        chdir: "{{ git_dir.path }}"

    - name: copy catalog source code
      copy:
        src: catalog/
        dest: "{{ git_dir.path }}/catalog/"

    - name: push catalog source code git repository
      shell: |
        git config user.email "rhdeveloper@redhat.com"
        git config user.name "rh-developer"
        git add --all
        git commit -m "connected catalog to inventory"
        git push origin master
      args:
        chdir: "{{ git_dir.path }}/catalog"

    - debug: 
      msg: After the catalog-build (pipeline) has execute run oc start-build catalog-release -n {{ dev_project }}  