apiVersion: v1
kind: Template
metadata:
  annotations:
    description: CoolStore Microservices - Inventory Deployment Template
    tags: microservice,nginx
  name: inventory-deployment
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${SERVICE_NAME}
    name: ${SERVICE_NAME}-${SERVICE_VERSION}
  spec:
    replicas: 1
    selector:
      version: ${SERVICE_VERSION}
      deploymentconfig: ${SERVICE_NAME}
    strategy:
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: ${SERVICE_NAME}
          version: ${SERVICE_VERSION}
          deploymentconfig: ${SERVICE_NAME}
      spec:
        containers:
        - image: docker.io/tqvarnst/openshift-nginx:latest
          imagePullPolicy: IfNotPresent
          name: ${SERVICE_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
            name: http
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: volume-inventory-config
            - mountPath: /usr/share/nginx/html/inventory
              name: volume-inventory-html
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
          - configMap:
              defaultMode: 420
              name: inventory-config
            name: volume-inventory-config
          - configMap:
              defaultMode: 420
              name: inventory-html
            name: volume-inventory-html
    test: false
parameters:
  - displayName: Service Name
    name: SERVICE_NAME
    required: true
    value: inventory
  - displayName: Service Version (e.g. v1)
    name: SERVICE_VERSION
    required: true
    value: v1
